/* DO NOT EDIT! this file was generated by graphql-codegen */
/* eslint-disable */
import * as Types from "./types.generated";

import { useMutation, UseMutationOptions } from "react-query";

function fetcher<TData, TVariables>(query: string, variables?: TVariables) {
  return async (): Promise<TData> => {
    const res = await fetch("http://localhost:3000/api", {
      method: "POST",
      ...{
        headers: { credentials: "include", "content-type": "application/json" },
      },
      body: JSON.stringify({ query, variables }),
    });

    const json = await res.json();

    if (json.errors) {
      const { message } = json.errors[0];

      throw new Error(message);
    }

    return json.data;
  };
}
export type UpdateDocsMutationVariables = Types.Exact<{
  id: Types.Scalars["String"];
  text: Types.Scalars["String"];
}>;

export type UpdateDocsMutation = {
  __typename?: "Mutation";
  updateDocs?:
    | { __typename?: "Docs"; id: string; text: string }
    | null
    | undefined;
};

export const UpdateDocsDocument = `
    mutation UpdateDocs($id: String!, $text: String!) {
  updateDocs(id: $id, text: $text) {
    id
    text
  }
}
    `;
export const useUpdateDocsMutation = <TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<
    UpdateDocsMutation,
    TError,
    UpdateDocsMutationVariables,
    TContext
  >
) =>
  useMutation<
    UpdateDocsMutation,
    TError,
    UpdateDocsMutationVariables,
    TContext
  >(
    "UpdateDocs",
    (variables?: UpdateDocsMutationVariables) =>
      fetcher<UpdateDocsMutation, UpdateDocsMutationVariables>(
        UpdateDocsDocument,
        variables
      )(),
    options
  );
